In [51]:
import pandas as pd
import os
os.getcwd()

'C:\\Users\\Atchyuta\\Downloads'

In [68]:
#!pip install gensim

  Created wheel for smart-open: filename=smart_open-4.2.0-py3-none-any.whl size=109632 sha256=353dfdabcc56405a11018dae28410c5e18beb5444d672f9f0a9097371c0f84ec
  Stored in directory: c:\users\atchyuta\appdata\local\pip\cache\wheels\25\88\e3\7cd51a6379cac37213cac47545a27688782752ff66351b953d
Successfully built smart-open


In [54]:
from sklearn import model_selection, preprocessing, linear_model, naive_bayes, metrics, svm
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn import decomposition, ensemble
import pandas, xgboost, numpy, textblob, string


In [55]:
data=pd.read_csv('C:\\Users\\Atchyuta\\Downloads\\train_data_tagging_wo_duration.csv')

In [5]:
data.head()

file_name                                       file_content  \
0  trans.2023.txt  Agent [silence] Customer all right Agent okay ...   
1  trans.2061.txt  Agent [noise] Customer [noise] Agent [silence]...   
2  trans.2067.txt  Agent [noise] Customer [noise] Agent well um w...   
3  trans.2163.txt  Agent [silence] Customer okay i was trying to ...   
4  trans.2313.txt  Agent [noise] Customer [silence] Agent [silenc...   

      file_tag  
0  Credit Card  
1  Credit Card  
2  Credit Card  
3  Credit Card  
4  Credit Card

In [56]:
train_x, Test_x, train_y, Test_y = model_selection.train_test_split(data['file_content'], data['file_tag'],test_size=0.20, random_state=42, stratify=data['file_tag'])


In [57]:
val_x, test_x, val_y, test_y = model_selection.train_test_split(Test_x, Test_y,test_size=0.20, random_state=42)

In [58]:
val_x.shape

(38,)

In [71]:
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
val_y = encoder.fit_transform(val_y)
test_y = encoder.fit_transform(test_y)


# Naive Bayes training based on Count Vectorizer

In [60]:
# create a count vectorizer object 
count_vect = CountVectorizer(analyzer='word', ngram_range=(2,5),stop_words='english')
count_vect.fit(data['file_content'])

CountVectorizer(ngram_range=(2, 5), stop_words='english')

In [61]:
xtrain_count =  count_vect.transform(train_x)
xtrain_count.shape
count_vect.vocabulary_


{'agent silence': 22634,
 'silence customer': 365999,
 'customer right': 104268,
 'right agent': 339572,
 'agent okay': 19071,
 'okay customer': 295560,
 'customer uh': 111779,
 'uh ve': 441641,
 've got': 455637,
 'got lot': 175890,
 'lot them_1': 261087,
 'them_1 laughter': 399965,
 'laughter them_1': 240394,
 'them_1 agent': 399503,
 'silence agent': 357918,
 'agent oh': 18161,
 'oh yes': 295060,
 'yes laughter': 488884,
 'laughter believe': 236142,
 'believe just': 49182,
 'just easy': 210633,
 'easy use': 143363,
 'use customer': 451337,
 'customer silence': 105542,
 'customer yeah': 116569,
 'yeah husband': 480695,
 'husband real': 199318,
 'real good': 329344,
 'good using': 173920,
 'using them_1': 453413,
 'agent laughter': 14711,
 'laughter oh': 239541,
 'oh believe': 292132,
 'believe uh': 49322,
 'uh say': 437746,
 'say uh': 350111,
 'uh uh': 440218,
 'uh rely': 437291,
 'rely customer': 336249,
 'customer don': 92476,
 'don them_1': 140010,
 'them_1 don': 399748,
 'don car

In [62]:
xvalid_count =  count_vect.transform(val_x)
xvalid_count.shape
count_vect.vocabulary_

{'agent silence': 22634,
 'silence customer': 365999,
 'customer right': 104268,
 'right agent': 339572,
 'agent okay': 19071,
 'okay customer': 295560,
 'customer uh': 111779,
 'uh ve': 441641,
 've got': 455637,
 'got lot': 175890,
 'lot them_1': 261087,
 'them_1 laughter': 399965,
 'laughter them_1': 240394,
 'them_1 agent': 399503,
 'silence agent': 357918,
 'agent oh': 18161,
 'oh yes': 295060,
 'yes laughter': 488884,
 'laughter believe': 236142,
 'believe just': 49182,
 'just easy': 210633,
 'easy use': 143363,
 'use customer': 451337,
 'customer silence': 105542,
 'customer yeah': 116569,
 'yeah husband': 480695,
 'husband real': 199318,
 'real good': 329344,
 'good using': 173920,
 'using them_1': 453413,
 'agent laughter': 14711,
 'laughter oh': 239541,
 'oh believe': 292132,
 'believe uh': 49322,
 'uh say': 437746,
 'say uh': 350111,
 'uh uh': 440218,
 'uh rely': 437291,
 'rely customer': 336249,
 'customer don': 92476,
 'don them_1': 140010,
 'them_1 don': 399748,
 'don car

In [67]:
xtest_count =  count_vect.transform(test_x)
xtest_count.shape
#count_vect.vocabulary_

(10, 489862)

In [63]:
# Naive Bayes on Count Vectors
nb_classifier=naive_bayes.MultinomialNB()
nb_classifier.fit(xtrain_count, train_y)


MultinomialNB()

In [28]:
train_y

array([3, 3, 5, 2, 3, 4, 5, 5, 5, 4, 5, 3, 3, 3, 2, 5, 4, 3, 1, 3, 2, 4,
       5, 2, 4, 0, 5, 2, 3, 4, 4, 3, 0, 3, 3, 3, 5, 4, 2, 4, 4, 5, 3, 3,
       2, 4, 1, 3, 1, 1, 1, 3, 4, 0, 1, 2, 2, 3, 5, 3, 5, 1, 3, 3, 2, 2,
       5, 5, 5, 2, 5, 3, 3, 5, 4, 3, 1, 2, 5, 4, 3, 3, 3, 4, 2, 1, 3, 4,
       3, 2, 3, 3, 5, 2, 3, 3, 2, 5, 1, 2, 4, 5, 3, 2, 1, 2, 4, 2, 0, 1,
       4, 3, 3, 4, 3, 4, 2, 3, 2, 4, 3, 4, 2, 1, 4, 2, 4, 3, 2, 1, 4, 4,
       5, 4, 4, 4, 4, 5, 1, 2, 3, 5, 5, 4, 5, 3, 5, 5, 3, 5, 5, 3, 4, 5,
       4, 2, 5, 5, 4, 5, 5, 5, 1, 5, 2, 4, 2, 5, 0, 4, 3, 4, 3, 4, 1, 3,
       2, 5, 5, 5, 1, 4, 3, 3, 2, 4, 5, 5, 2, 3, 4, 4])

In [64]:
predictions = nb_classifier.predict(xtrain_count)
metrics.accuracy_score(predictions, train_y)

1.0

In [65]:
predictions = nb_classifier.predict(xvalid_count)

In [66]:
metrics.accuracy_score(predictions, val_y)

0.7368421052631579

In [72]:
predictions = nb_classifier.predict(xtest_count)
metrics.accuracy_score(predictions, test_y)

0.1

In [69]:
predictions

array([3, 2, 4, 3, 5, 4, 3, 5, 4, 3])

In [70]:
test_y

190    Family Finance
26        Credit Card
101      Job Benefits
188    Family Finance
61              Taxes
137      Job Benefits
185    Family Finance
90              Taxes
147      Job Benefits
58              Taxes
Name: file_tag, dtype: object

In [30]:
test_y = encoder.fit_transform(test_y)
test_count =  count_vect.transform(test_x)



In [31]:
test_predictions = nb_classifier.predict(test_count)

In [32]:
metrics.accuracy_score(test_predictions, test_y)

0.1

In [33]:
test_predictions

array([3, 2, 4, 3, 5, 4, 3, 5, 4, 3])

In [34]:
test_y

array([1, 0, 2, 1, 3, 2, 1, 3, 2, 3])

# Naive Bayes training based on TF-IDF

In [73]:
# characters level tf-idf
tfidf_vect_ngram = TfidfVectorizer(analyzer='word', token_pattern=r'\w{1,}', ngram_range=(2,3), max_features=30000)
tfidf_vect_ngram.fit(data['file_content'])
xtrain_tfidf_ngram =  tfidf_vect_ngram.transform(train_x) 
xvalid_tfidf_ngram =  tfidf_vect_ngram.transform(val_x)

In [74]:
nb_classifier=naive_bayes.MultinomialNB()
nb_classifier.fit(xtrain_tfidf_ngram, train_y)

MultinomialNB()

In [75]:
predictions = nb_classifier.predict(xtrain_tfidf_ngram)
metrics.accuracy_score(predictions, train_y)

0.7864583333333334

In [38]:
predictions = nb_classifier.predict(xvalid_tfidf_ngram)

In [39]:
metrics.accuracy_score(predictions, val_y)

0.47368421052631576

In [40]:
xtest_tfidf_ngram =  tfidf_vect_ngram.transform(test_x)

In [41]:
predictions = nb_classifier.predict(xtest_tfidf_ngram)

In [42]:
metrics.accuracy_score(predictions, test_y)

0.2

In [43]:
predictions

array([3, 3, 3, 3, 5, 3, 3, 3, 4, 3])

In [44]:
test_y

array([1, 0, 2, 1, 3, 2, 1, 3, 2, 3])

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import os
from sklearn.model_selection import train_test_split

from keras.layers import concatenate
from sklearn.metrics import mean_squared_error
import nltk



import pandas as pd
import numpy as np
import re
from nltk import word_tokenize          
from nltk.corpus import stopwords
from keras.layers.embeddings import Embedding
from keras.layers.recurrent import LSTM
from keras.layers import Input, Bidirectional,TimeDistributed
from keras.models import Model
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from keras.layers import Dense, Dropout
from keras.optimizers import Adam
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint

Using TensorFlow backend.
D:\Anaconda3\envs\keras-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Anaconda3\envs\keras-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Anaconda3\envs\keras-tf\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Anaconda3\envs\keras-tf\lib\site-packages\tensorflow\python\framework\d

In [6]:
data['file_tag'].unique()

array(['Credit Card', 'Bank Bailout', 'Taxes', 'Job Benefits',
       'Family Finance', 'Budget'], dtype=object)

In [7]:
def buildVocabulary(sentence):
    text = list(set(sentence))
    tokenizer = Tokenizer(lower=False, split=' ')
    tokenizer.fit_on_texts(text)
    return tokenizer

In [8]:
def cleanSentence(sentence):
     sentence_clean= re.sub("[^a-zA-Z0-9]"," ", str(sentence))
     sentence_clean = sentence_clean.lower()
     tokens = word_tokenize(sentence_clean)
     stop_words = set(stopwords.words("english"))
     sentence_clean_words = [w for w in tokens if not w in stop_words]
     return ' '.join(sentence_clean_words)

In [9]:
nltk.download('punkt')
nltk.download('stopwords')

#clean the sentence 
data['clean_file_content'] = list(map(cleanSentence, data['file_content']))

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Atchyuta\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Atchyuta\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [10]:
corpus_text1 = '\n'.join(data['clean_file_content'])
sentences = corpus_text1.split('\n')

In [11]:
tokenizer = buildVocabulary(sentences)


In [12]:
tokenizer

In [13]:
vocab_size = len(tokenizer.word_index) + 1


In [14]:
vocab_size

8216

In [57]:
sentences

['agent silence customer right agent okay customer uh got lot 1 laughter many 1 agent silence agent oh yes laughter believe easy use customer silence customer yeah well husband real good using 1 agent silence agent laughter oh believe uh mine would say uh uh seem rely much customer silence customer 1 carry 1 carries 1 try take 1 away agent silence agent laughter customer silence agent um uh vocalized noise know seem uh use cash fact rather carry cards would uh cash customer yeah well got spot trouble uh using uh credit cards gas agent silence agent uh yes customer uh got us trouble agent silence agent yes uh real easy watch customer silence customer laughter yeah agent fact yeah uh laughter understand predicament customer silence agent silence agent um agent silence agent um know made easy accessible everything buy customer atm machines agent silence agent oh yes customer silence customer things gets us agent silence agent plus end forgetting write customer silence agent silence custom

In [15]:
data['word_count'] = data['clean_file_content'].apply(lambda x: len(str(x).split(" ")))
#incidents_data['word_count'] = incidents_data['short_description'].apply(lambda x: len(str(x).split(" ")))
data[['clean_file_content','word_count']].head(11)

clean_file_content  word_count
0   agent silence customer right agent okay custom...        1320
1   agent noise customer noise agent silence custo...        1676
2   agent noise customer noise agent well um credi...         576
3   agent silence customer okay trying get childre...         431
4   agent noise customer silence agent silence cus...        1080
5   agent silence customer right agent well like t...        1314
6   agent noise customer noise agent silence custo...        1329
7   agent silence customer noise customer okay um ...        1000
8   agent noise customer noise customer right agen...         999
9   agent silence customer noise customer probably...        1484
10  agent noise customer noise agent silence custo...        1527

In [61]:
type(data['word_count'])

pandas.core.series.Series

In [16]:
data['word_count'].max()

1676

In [17]:
def getTrainSequences(sentence, tokenizer,seq_maxlen):
    sent1 = tokenizer.texts_to_sequences(sentence)
    #sent_maxlen = max([len(s) for s in sent1])
    #seq_maxlen = max([sent_maxlen])
    return np.array(pad_sequences(sent1, maxlen=seq_maxlen))

In [18]:
#get sequences for each sentence pair tuple
train_data_need = getTrainSequences(sentences, tokenizer,seq_maxlen=1680)

In [19]:
train_data_need.shape


(240, 1680)

In [20]:
sentences_w2c = [line.split(' ') for line in sentences]


In [21]:
from gensim.models import Word2Vec

model_w2v = Word2Vec(sentences_w2c, size=100, window=5, min_count=0, workers=4)
vectors = model_w2v.wv
#vectors.save("custom_w2v_vec.bin")

In [22]:
print(len(list(vectors.vocab)))


8215


In [23]:
word_embed_size = 100


In [24]:
def getEmbeddingWeightMatrix_w2vec(w2vec_vectors,word2idx):    
    embedding_matrix = np.zeros((len(word2idx)+1, word_embed_size))
    for word, i in word2idx.items():
        embedding_vector = w2vec_vectors[word]
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector
    return embedding_matrix

In [25]:
#get embedding layer weight matrix
embedding_weight_matrix = getEmbeddingWeightMatrix_w2vec(vectors, tokenizer.word_index)

In [26]:
embedding_weight_matrix.shape

(8216, 100)

In [27]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
data["file_tag_encoder"] = lb_make.fit_transform(data.file_tag.astype(str))
data[["file_tag", "file_tag_encoder"]].head(11)

file_tag  file_tag_encoder
0   Credit Card                 2
1   Credit Card                 2
2   Credit Card                 2
3   Credit Card                 2
4   Credit Card                 2
5   Credit Card                 2
6   Credit Card                 2
7   Credit Card                 2
8   Credit Card                 2
9   Credit Card                 2
10  Credit Card                 2

In [28]:
train_x, Test_x, train_y, Test_y = model_selection.train_test_split(train_data_need, data['file_tag_encoder'],test_size=0.20, random_state=42, stratify=data['file_tag_encoder'])


In [29]:
val_x, test_x, val_y, test_y = model_selection.train_test_split(Test_x, Test_y,test_size=0.20, random_state=42)

In [30]:
from keras.utils import np_utils
y1_train1 = np_utils.to_categorical(train_y)
y1_test = np_utils.to_categorical(test_y)
y1_val=np_utils.to_categorical(val_y)

In [31]:
import pandas as pd
import numpy as np

from keras.preprocessing.text import Tokenizer
from keras.engine.topology import Layer
from keras import initializers as initializers, regularizers, constraints
from keras.callbacks import Callback
from keras.layers import Embedding, Input, Dense, LSTM, GRU, Bidirectional, TimeDistributed
from keras import backend as K
from keras.models import Model

from sklearn.metrics import roc_auc_score


def dot_product(x, kernel):
    
    if K.backend() == 'tensorflow':
        return K.squeeze(K.dot(x, K.expand_dims(kernel)), axis=-1)
    else:
        return K.dot(x, kernel)

class AttentionWithContext(Layer):    

    def __init__(self,
                 W_regularizer=None, u_regularizer=None, b_regularizer=None,
                 W_constraint=None, u_constraint=None, b_constraint=None,
                 bias=True, **kwargs):

        self.supports_masking = True
        self.init = initializers.get('glorot_uniform')

        self.W_regularizer = regularizers.get(W_regularizer)
        self.u_regularizer = regularizers.get(u_regularizer)
        self.b_regularizer = regularizers.get(b_regularizer)

        self.W_constraint = constraints.get(W_constraint)
        self.u_constraint = constraints.get(u_constraint)
        self.b_constraint = constraints.get(b_constraint)

        self.bias = bias
        super(AttentionWithContext, self).__init__(**kwargs)

    def build(self, input_shape):
        assert len(input_shape) == 3

        self.W = self.add_weight((input_shape[-1], input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_W'.format(self.name),
                                 regularizer=self.W_regularizer,
                                 constraint=self.W_constraint)
        if self.bias:
            self.b = self.add_weight((input_shape[-1],),
                                     initializer='zero',
                                     name='{}_b'.format(self.name),
                                     regularizer=self.b_regularizer,
                                     constraint=self.b_constraint)

        self.u = self.add_weight((input_shape[-1],),
                                 initializer=self.init,
                                 name='{}_u'.format(self.name),
                                 regularizer=self.u_regularizer,
                                 constraint=self.u_constraint)

        super(AttentionWithContext, self).build(input_shape)

    def compute_mask(self, input, input_mask=None):
        # do not pass the mask to the next layers
        return None

    def call(self, x, mask=None):
        uit = dot_product(x, self.W)

        if self.bias:
            uit += self.b

        uit = K.tanh(uit)
        ait = dot_product(uit, self.u)

        a = K.exp(ait)

        if mask is not None:
            a *= K.cast(mask, K.floatx())

        
        a /= K.cast(K.sum(a, axis=1, keepdims=True) + K.epsilon(), K.floatx())

        a = K.expand_dims(a)
        weighted_input = x * a
        return K.sum(weighted_input, axis=1)

    def compute_output_shape(self, input_shape):
        return input_shape[0], input_shape[-1]

In [32]:
seq_maxlen=1680
word_embed_size = 100


In [33]:
y1_train1.shape[1]

6

In [34]:
train_x.shape

(192, 1680)

In [35]:
##Model Building on LSTM and  Attention layer
input = Input(shape=(train_x.shape[1],))

inner = Embedding(input_dim=vocab_size, output_dim=word_embed_size, 
                   input_length=seq_maxlen, weights=[embedding_weight_matrix], 
                   trainable = True) (input)

inner = LSTM(100, return_sequences=True)(inner)
inner = Dropout(0.3)(inner)
# compute importance for each step
#inner = TimeDistributed(Dense(100))(inner) 
words_att = AttentionWithContext()(inner)

inner = Dense(100, activation='relu')(words_att)
#inner = Dense(40, activation='relu')(inner)
output = Dense(y1_train1.shape[1], activation='softmax')(inner)

model_a = Model(inputs = input, outputs = output)

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [36]:
model_a.save('my_lstm_model.h5')

In [37]:
import keras

model_a1 = keras.models.load_model('my_lstm_model.h5', custom_objects={'AttentionWithContext':AttentionWithContext()})

D:\Anaconda3\envs\keras-tf\lib\site-packages\keras\models.py:282: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [38]:
print(model_a1.summary())
model_a1.compile(Adam(lr=0.01), 'categorical_crossentropy', metrics=['accuracy'])
#model_a.load_weights('/var/www/projects/nehru/text_classification/code/model_incidents_attention_lstm_word_vec_100d_n1.h5')

save_weights = ModelCheckpoint('model_doc_tagging_attention_lstm_word_vec_100d_new.h5', monitor='val_loss', save_best_only=True)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 1680)              0         
_________________________________________________________________
embedding_1 (Embedding)      (None, 1680, 100)         821600    
_________________________________________________________________
lstm_1 (LSTM)                (None, 1680, 100)         80400     
_________________________________________________________________
dropout_1 (Dropout)          (None, 1680, 100)         0         
_________________________________________________________________
attention_with_context_1 (At (None, 100)               10200     
_________________________________________________________________
dense_1 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_2 (Dense)              (None, 6)                 606       
Total para

In [39]:
from keras.models import model_from_json
model_json = model_a1.to_json()
with open("model_incident_classification_lstm_attention.json", "w") as json_file:
    json_file.write(model_json)

In [41]:
history = model_a1.fit(x=train_x, y=y1_train1, batch_size=32,
          epochs=30, validation_data=(val_x, y1_val), callbacks=[save_weights])

Instructions for updating:
Use tf.cast instead.
Train on 192 samples, validate on 38 samples
Epoch 1/30
192/192 [==============================] - 9s 49ms/step - loss: 1.7561 - acc: 0.2552 - val_loss: 1.6636 - val_acc: 0.2368
Epoch 2/30
192/192 [==============================] - 8s 43ms/step - loss: 1.6739 - acc: 0.2083 - val_loss: 1.6700 - val_acc: 0.2105
Epoch 3/30
192/192 [==============================] - 8s 43ms/step - loss: 1.6587 - acc: 0.1979 - val_loss: 1.6563 - val_acc: 0.2105
Epoch 4/30
192/192 [==============================] - 8s 43ms/step - loss: 1.6533 - acc: 0.2344 - val_loss: 1.6506 - val_acc: 0.2632
Epoch 5/30
192/192 [==============================] - 8s 43ms/step - loss: 1.6506 - acc: 0.2604 - val_loss: 1.6515 - val_acc: 0.2632
Epoch 6/30
192/192 [==============================] - 9s 44ms/step - loss: 1.6504 - acc: 0.2188 - val_loss: 1.6563 - val_acc: 0.2105
Epoch 7/30
192/192 [==============================] - 9s 45ms/step - loss: 1.6455 - acc: 0.2292 - val_loss: 1

array([[   0,    0,    0, ...,   37,    1,    3],
       [   0,    0,    0, ...,  601,    2,  732],
       [   0,    0,    0, ...,  338, 4801, 3496],
       ...,
       [   0,    0,    0, ...,  492,    1,    3],
       [   0,    0,    0, ...,    1,    3,    2],
       [   0,    0,    0, ...,  189,  189,    9]])

In [43]:
predicted_lstm=model_a1.predict(test_x)
predicted_lstm=predicted_lstm.argmax(axis=-1)
y1_test=y1_test.argmax(axis=-1)

In [45]:
accuracy1=np.mean(predicted_lstm==y1_test)


In [46]:
accuracy1

0.3

In [47]:
y1_test

array([3, 2, 4, 3, 5, 4, 3, 5, 4, 5], dtype=int64)

In [48]:
predicted_lstm

array([3, 2, 3, 1, 5, 0, 4, 1, 1, 2], dtype=int64)